export { default as InforceLogoDark } from './InforceLogoDark'
export { default as InforceLogoLight } from './InforceLogoLight'
export { default as StarIcon } from './StarIcon'
export { default as СlutchIcon } from './СlutchIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as SkypeIcon } from './SkypeIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as LinkedInIcon } from './LinkedInIcon'
export { default as SunEllipseIcon } from './SunEllipseIcon'
export { default as StrategyIcon } from './StrategyIcon'
export { default as MobileIcon } from './MobileIcon'
export { default as RocketIcon } from './RocketIcon'
export { default as SorryIcon } from './SorryIcon'
export { default as OopsIcon } from './OopsIcon'
export { default as PanelIcon } from './PanelIcon'
export { default as PrevBtnIcon } from './PrevBtnIcon'
export { default as NextBtnIcon } from './NextBtnIcon'
export { default as StrategyIconLarge } from './StrategyIconLarge'
export { default as SwipeIcon } from './SwipeIcon'
export { default as PlayerIcon } from './PlayerIcon'
export { default as Test } from './Test'

// process
export { default as DrawingIcon } from './iconsForProcessPage/DrawingIcon'
export { default as LeftSideLinesIcon } from './iconsForProcessPage/LeftSideLinesIcon'
export { default as RightSideLinesIcon } from './iconsForProcessPage/RightSideLinesIcon'
export { default as Quots } from './iconsForProcessPage/Quots'
