export { default as FormSection } from './FormSection'
export { default as GoalSection } from './GoalSection'
export { default as SectionWithSvgAndText } from './SectionWithSvgAndText'
export { default as SliderSection } from './SliderSection'
export { default as VideoSection } from './VideoSection'
export { default as YouNeedUsSection } from './YouNeedUsSection'
export { default as YouNeedUsWithSvg } from './YouNeedUsWithSvg'
